#!/bin/sh
# Regenerates BrowserKit's embedded public suffix table from the real list.
#
# `PublicSuffix.swift` ships a curated subset on purpose — the full list is
# ~9,000 rules and changes weekly, and a stale embedded copy is worse than a
# small current one. This script is the promised escape hatch: run it before
# v1 and on a schedule after, then review the diff.
#
# It writes a *candidate* file beside the real one rather than overwriting it.
# The table is security-relevant — every rule decides which sites share a
# credential — so it gets read by a person before it lands.
set -eu

root="$(cd "$(dirname "$0")/.." && pwd)"
out="$root/BrowserKit/Sources/BrowserKit/Passwords/PublicSuffixTable.candidate.swift"
src="https://publicsuffix.org/list/public_suffix_list.dat"

echo "Fetching $src"
raw="$(mktemp)"
trap 'rm -f "$raw"' EXIT
curl -fsSL "$src" -o "$raw"

total=$(grep -cvE '^(//|$)' "$raw" || true)
echo "Fetched $total rules."

# Only multi-label rules are emitted. Single-label TLDs are already answered by
# the PSL's own default rule ("if no rule matches, the prevailing rule is *"),
# so listing 1,400 of them would be 1,400 more strings to keep current for no
# change in behaviour. See the doc comment in PublicSuffix.swift.
{
	echo "// Generated by Tools/update-public-suffix-list.sh on $(date -u +%Y-%m-%d)."
	echo "// Source: $src"
	echo "//"
	echo "// Review this diff before folding it into PublicSuffix.swift: every rule here"
	echo "// decides which sites may share a saved credential (TODO.md §14.3)."
	echo ""
	echo "extension PublicSuffix {"
	echo "    static let generatedExceptions: Set<String> = ["
	grep -E '^!' "$raw" | sed 's/^!//' | sort -u | sed 's/^/        "/; s/$/",/'
	echo "    ]"
	echo ""
	echo "    static let generatedRules: Set<String> = ["
	grep -vE '^(//|!|$)' "$raw" | grep -F '.' | sort -u | sed 's/^/        "/; s/$/",/'
	echo "    ]"
	echo "}"
} > "$out"

echo "Wrote $out"
echo "Review it, then update maxRuleLabels in PublicSuffix.swift if the longest"
echo "rule grew: $(grep -vE '^(//|!|$)' "$raw" | awk -F. '{print NF}' | sort -rn | head -1) labels in this list."
